#!/bin/bash

BRANCH_NAME=`git symbolic-ref HEAD --short`
BRANCH_MAP=`cat .git/hooks/branch-tickets.map`
COMMIT_MESSAGE=`cat "$1"`

regex="$BRANCH_NAME ([0-9]+)"
if [[ $BRANCH_MAP =~ $regex ]]
then
    echo "$COMMIT_MESSAGE #${BASH_REMATCH[1]}" > $1
fi
